apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitbook
  labels:
    app: gitbook
  namespace: development
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gitbook
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: development
      containers:
      - name: gitbook
        image: "myrepoimage/gitbook:version"
        ports:
        - name: http
          containerPort: 4000
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
            - name: X-Skip-Logging
              value: "true"
          initialDelaySeconds: 15
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: gitbook
  labels:
    app: gitbook
  namespace: development
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: gitbook

---

apiVersion: apps/v1beta1
kind: Ingress
metadata:
  name: gitbook
  labels:
    app: gitbook
  namespace: development
spec:
  rules:
  - host: gitbook.mydomain.com
    http:
      paths:
      - backend:
          serviceName: gitbook
          servicePort: http